language: node_js
node_js:
  - "14"
sudo: required
services:
  - docker

branches:
  only:
    - master

before_install:
  - docker build -t balram02/apm -f Dockerfile.dev .
  # script:
#   - docker run balram02/APM
